### PR TITLE
Starting to set up deploy scripts for strategies

### PR DESCRIPTION
**Pull request by naps62**
Setup an initial deploy script for USTStrategy, for now deployable only on mainnet (because I don't know full config options)

### CODE REVIEW

**Comment by naps62** [comment]
@ryuheimat could you review the `deployConfigs` mapping? I'm not sure if I used the right addresses, and who the owners will be for each vault / strategy

**Comment by ryuheimat** [comment]
There are underlying tokens on ropsten testnet, so i don't think we need mock tokens.

**Comment by naps62** [comment]
that's not what I asked :/ I was asking about the multisig, treasury, etc

And about those underlying tokens. Which ones are they, and how can I get them? Are you talking about public tokens, or ones that we deployed?

**Comment by ryuheimat** [comment]
> And about those underlying tokens. Which ones are they, and how can I get them? Are you talking about public tokens, or ones that we deployed?

Those are public tokens which ethAnchor is using on ropsten testnet.

**Comment by naps62** [comment]
@ryuheimat I'm not sure what this means for development. how easy is it get those tokens? e.g.: for our frontend developers to test, they'll need to get UST, bridge to ETH & swap? sounds like a very complicated process for them, that we should try to simplify

**Comment by naps62** [comment]
well, I was thinking maybe we can also deploy MockEthAnchor in ropsten and use that in order to better be able to test flows

**Comment by ryuheimat** [comment]
Using EthAnchor's testnet is more comfortable i think, because it is actually interact with anchor terra testnet protocol with terra bridge, etc.
I have 100k testnet UST token, so i think it's enough to test.

**Review by gabrielpoca — APPROVED** [review]
Ty! I was just talking about this with Alvaro and Joao, we need to setup a "real" test environment. From what I'm reading it seems that we can use a Anchor's strategy on the testnet?

**Comment by naps62** [comment]
Yes. and Ryuhei apparently has enough testnet UST to distribute a bit (he sent me 1000$)

**Pull request merged**
